/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as CodeRouteImport } from './routes/code'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki.index'
import { Route as WikiLearningPlanRouteImport } from './routes/wiki.learning-plan'
import { Route as WikiGraphRouteImport } from './routes/wiki.graph'
import { Route as WikiVideoIdRouteImport } from './routes/wiki.video.$id'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiRoute,
} as any)
const WikiLearningPlanRoute = WikiLearningPlanRouteImport.update({
  id: '/learning-plan',
  path: '/learning-plan',
  getParentRoute: () => WikiRoute,
} as any)
const WikiGraphRoute = WikiGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => WikiRoute,
} as any)
const WikiVideoIdRoute = WikiVideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => WikiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/podcast': typeof PodcastRoute
  '/showcase': typeof ShowcaseRoute
  '/wiki': typeof WikiRouteWithChildren
  '/wiki/graph': typeof WikiGraphRoute
  '/wiki/learning-plan': typeof WikiLearningPlanRoute
  '/wiki/': typeof WikiIndexRoute
  '/wiki/video/$id': typeof WikiVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/podcast': typeof PodcastRoute
  '/showcase': typeof ShowcaseRoute
  '/wiki/graph': typeof WikiGraphRoute
  '/wiki/learning-plan': typeof WikiLearningPlanRoute
  '/wiki': typeof WikiIndexRoute
  '/wiki/video/$id': typeof WikiVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/podcast': typeof PodcastRoute
  '/showcase': typeof ShowcaseRoute
  '/wiki': typeof WikiRouteWithChildren
  '/wiki/graph': typeof WikiGraphRoute
  '/wiki/learning-plan': typeof WikiLearningPlanRoute
  '/wiki/': typeof WikiIndexRoute
  '/wiki/video/$id': typeof WikiVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/code'
    | '/podcast'
    | '/showcase'
    | '/wiki'
    | '/wiki/graph'
    | '/wiki/learning-plan'
    | '/wiki/'
    | '/wiki/video/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code'
    | '/podcast'
    | '/showcase'
    | '/wiki/graph'
    | '/wiki/learning-plan'
    | '/wiki'
    | '/wiki/video/$id'
  id:
    | '__root__'
    | '/'
    | '/code'
    | '/podcast'
    | '/showcase'
    | '/wiki'
    | '/wiki/graph'
    | '/wiki/learning-plan'
    | '/wiki/'
    | '/wiki/video/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRoute
  PodcastRoute: typeof PodcastRoute
  ShowcaseRoute: typeof ShowcaseRoute
  WikiRoute: typeof WikiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/learning-plan': {
      id: '/wiki/learning-plan'
      path: '/learning-plan'
      fullPath: '/wiki/learning-plan'
      preLoaderRoute: typeof WikiLearningPlanRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/graph': {
      id: '/wiki/graph'
      path: '/graph'
      fullPath: '/wiki/graph'
      preLoaderRoute: typeof WikiGraphRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/video/$id': {
      id: '/wiki/video/$id'
      path: '/video/$id'
      fullPath: '/wiki/video/$id'
      preLoaderRoute: typeof WikiVideoIdRouteImport
      parentRoute: typeof WikiRoute
    }
  }
}

interface WikiRouteChildren {
  WikiGraphRoute: typeof WikiGraphRoute
  WikiLearningPlanRoute: typeof WikiLearningPlanRoute
  WikiIndexRoute: typeof WikiIndexRoute
  WikiVideoIdRoute: typeof WikiVideoIdRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiGraphRoute: WikiGraphRoute,
  WikiLearningPlanRoute: WikiLearningPlanRoute,
  WikiIndexRoute: WikiIndexRoute,
  WikiVideoIdRoute: WikiVideoIdRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  PodcastRoute: PodcastRoute,
  ShowcaseRoute: ShowcaseRoute,
  WikiRoute: WikiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
