/**
 * Centralized video configuration
 * Single source of truth for all video IDs across the app
 */

import { z } from 'zod'

// Schema for validating video metadata responses
export const VideoMetadataSchema = z.object({
  id: z.string(),
  title: z.string(),
  views: z.number().nonnegative(),
  date: z.string().datetime(),
  tags: z.array(z.string()).optional()
})

export const VideoMetadataResponseSchema = z.object({
  videos: z.array(VideoMetadataSchema),
  source: z.enum(['api', 'fallback', 'placeholder']).optional(),
  timestamp: z.string().datetime().optional()
})

export type VideoMetadata = z.infer<typeof VideoMetadataSchema>
export type VideoMetadataResponse = z.infer<typeof VideoMetadataResponseSchema>

export const VIDEO_CONFIG = {
  korea: [
    'V2cZl5s4EKU',
    'L9sxbq8ugoU',
    'vNHblhm9oQo',
    '4h84JgKkt94',
    'CASZX56r-tk',
    'EvcUSPWkOA8',
    'JlPl9MskqJM',
    'drVBXipEOAs',
    'awa_UWXFOao',
    'nxuaOP3C1Ns',
    'QLcNRIHYmj0',
    'rwNfzJanPmk',
    'rxQvDuohbt8',
    'kvdBJSRUchA',
    'oSqbvvcADmI',
    'vH8kEIlJXf0',
    'z76NXRg1YWs',
    'ApeNMU7KDH0',
    '7-mEDyQsJlI',
    't-WvRifOu-E'
  ],
  finance: [
    'ZQyL7MT7k60',
    '8vJLWsfheRE',
    'GmUKi-ZPOYU',
    'P-QVC5lOMbU',
    'UGQ-ItKwJNw',
    '3bcmjx5F5Xs',
    '9xDzB24tO4I',
    'rjhabJ8Bx5U',
    'Dx8pFmojxL4',
    'UorjmtDDRgQ',
    'SRwWBbsaQH4',
    'M_NbzCCHFp0',
    '1smShC18TWA',
    'vzwjAlEz_bI',
    'YYVxMSqBqe8',
    'l9UUqD2Bz2E',
    'HFmkEvxyJE4',
    'hnMR8rdGCnU',
    'G-vvSNwm-jE',
    '_LrmdP64y6A',
    '2NoJVXPpcco',
    '_4BC0zHGYTw',
    '9z6mOWQgU84',
    'bn-Nvmxgur8',
    'ybR0RxXj2_M',
    'K1O4kHjFJaQ',
    'MBnVggs6k5g',
    'nfD3KzIriM8',
    's1BoGn9r7oE',
    'EMXUbohWsWs',
    'KBfVy5-M-5k',
    'MDNRiJN7aEg',
    'nnL78ZVifZU',
    'tPDFgVAp4c4',
    'J4nERLAJIbs',
    'md9nXDH1u7Q',
    'BNznoJHQDW0'
  ],
  kubernetes: ['78Sm363xiIw', 'PofJfj6nRuw', 'hvkvH7i8NLc', 'LxI5YjCUswI', '9ga0NT3ZohQ', 'u_ooo1WDAc8', 'WrZN5AgpaW4', 'V9tvg6Yg3m4', '4YsX6tYi5x4', '-e7kvcUXxtw', 'eaPXjvB194w', 'quD4pyCwKB4', '2ksi8K7wg3I', 'eZNBXDUc8OQ', 'p9LNSeAt5Zw', 'PMgUhFxrjPc', 'nomIVRSBEG4', 'mGMaqTvWrCc', 'oHdhgeF4wlI', 'a8heWpae5p0', 'KdLQEv3Tiiw', 'WRpjJV4SUKc', '7Dchx829X_M', '7iWL5-0C66s', 'BiYKKVsJROk', 'fMjflPvjaJ8', 'lexZnOlyml0', 'QE51ybyrQDM', 'RLlEbcXO6k8', 'tcrNdx1yH_E', 'n-Yt33ZdEHw', 'nJ10P-fRqZQ', 'to1PClyd0YA', 'LUOX5xkSyi0', 'u60g2nMtVi4', 'F09-7mNt3F4', '1PH7UB24xps', 'Hd767VA7Z-0', 'aiYBPCkvhes', 'Pxh2PcNx9W8', '3hSdKvqPcSE', 'y3WwL48DLYw', 'ORjARjbukhY', 'rk_3xU9OF-k', 'mYClRFIlsFc', '7eoxSgjwYlM', '5Ztm7JNVa8E', 'P_xUJi_qt-Q', 'okVlu1qseI4', 'eI2DXGISpbk', 'MIZ0ATwu7C0', 'rgY4KTMFOMs', 'BsiQrEaF3kU', 'Q4qm1hvVR2A', 'WHonjixQgBY', 'KpSjLQpswW4', '4b-H6ZaoNUE', '_sxPf3tHq3s', '0U-SUJCmKAU', 'VxWyvAO3qb8', 'A4-foXsdQiA', 'C6wLm6NRZW4', 'ctKLD4d146g', 'OnwiaDRj1-k', 'R2zktRqz81U', 'N4nRAfBZ3BE', 'C5HqbzLRYZ0', 'rJTUB-u8U2Y', 'A7eoKD5m6Ek', 'snRi_JET1bg', '8ycnldvJmuA', 'ftODZr2_V5Q', 'sZRIbxwHSCo', 'JrCT7Xu-aGU', 'hs7CiLpLgnY'],
  development: [
    'ISLXOiFqC50',
    'ElxPa5vX9Kc',
    'Z_TABCzmoQ0',
    '240fOdSvnpk',
    'KXx_6BhzOFE',
    'xwEN7oZFvdw',
    'fWuJSwkdH6I',
    's6wmtsAWvCw',
    'cuA7G01T7_U',
    '3jMQWDNqsro',
    'r1rhrISQXeA',
    'XHQGmyffO-s',
    'SNgYSLZ2Ck4',
    'JMk8y25qo2M',
    'i8wjbDfxZTY',
    'uiU9K1hIQBo',
    'JNHxVHyzWdE',
    'CqBZBJTAo3I',
    'L4YBdUVCFd4',
    'cDNqrUa260k',
    'd3JxtD__-L0',
    '78hLFt3_Gh4',
    'Jf1VkCXsmwU',
    'aQpGQClZSvc',
    '7LynLmseNRk',
    '3ONqqMoLy0s',
    'FIelcuTti-I',
    'Fqokr0P2_ag',
    'yXZnBtdDTFk',
    'S3Vc_R-HezY',
    'nwAdb-PyRlo',
    'zWuFvi-0Go4',
    'TpyKC8_30xs',
    'xiTVDbJscik',
    'V6Ru7YYLneE',
    'B7MMdnv3y1M',
    'kSQtbPEtDkY',
    'KR188eZ9gRE',
    '6M76N3jhh1Q',
    'htpvlYnX77w',
    'jrD_LGNsJXM',
    'ytA6gw6Tgaw',
    'bAoDvQgmGjM',
    'Gy-ky1pAF0U',
    'BhzeYd4aqOQ',
    '9HUPNhA3OrI',
    'i2YEYgVx0AA',
    'ZbZdm5Opbno',
    'n9Ebc-0E478',
    'uz8nmkTPEpg',
    'AvysIjFrTEw',
    'ZfAc2pqcS-4',
    'B81dHVYOYJA',
    'Qi_vpz_5j7g',
    '8PaVKQoDReY',
    'jOw6d5zH658',
    'qAHyv6G3a7M',
    '_bFOZ51Q55Y',
    'SuuZW_fuEFc',
    'LnJbrb0EUaE',
    'ZUINk3dp9eA',
    '85pyYZFJ6_s',
    'eJlXFaZNP6g',
    'E30riOZ-YVo',
    'UOOkDh4RUbE',
    '173Y2uPljgo',
    'QOYXBkMcnYk',
    'd1MH4nza95g',
    '07aDX5YB-ao',
    'DwAOCljoNoc',
    '90hw9qwXbbw',
    'J4iGUAXcAOA',
    'xlwu0YwE3_Q',
    'oqi_jJl3tAQ',
    'GERT8PoS9Qk',
    '4aAyFYemYD8',
    'i1HT5UIccTs',
    'R3n8UxyD7mc',
    'EWwk29GzHgg',
    'BQ4wab0UtLg',
    'yAeM2vpPWeM',
    'xvqZFPf5X60',
    'fNN88ZXWYKU',
    'L9ypC5863yA',
    'z_W9dX6fliM',
    'NhYb7QkBdMs',
    'pgTCcVO4gfg',
    'xkHQhOgapfY',
    'FM6zp63maS8',
    'vtzEOYX_8k8',
    'wKzz0jKiScM',
    'feWjiYzQQ-k',
    'wZC8NL32yfg',
    'izLrX-02IQk',
    'q-6cUColzQQ',
    'VHuQi_1t5qQ',
    'E8f87EV4k3A',
    'lsjfczYFBeQ',
    'X65YHZUnFq0',
    'hTEG3TsuUPQ',
    'Qg6vQrmCilg',
    'j8lMpSezavQ',
    'a1hIA6KQUFE',
    'tyR8SdHpOeY',
    '-tZGlR8Zztg',
    'QC-vaMcjq3M',
    's585HlqiyMQ',
    'LackTxguXFg',
    'TEGFwsAcxK8',
    'BzvpasWYESU',
    'MuDJGnGTn3k',
    'am9FvNiJ24M',
    'ea5lpF3RyzE',
    'IYfTi_HNDl4',
    'dDtVuJXVYJk',
    'fv61JXUCbeo',
    'T-NdEF6btbg',
    'BT08SXPvV6U',
    'z2SA6P7WNoc',
    '54lO6XE-AeQ',
    'YoIXlqspLWE',
    'JWeu5aqAkR0',
    'oUTf9j6fWJo',
    'Y0DQGVALb7I',
    '4i-ruNPOtB4',
    'F59lTcC6xJ0',
    'Qv9X3ZY474U',
    'uU46ltIELqk',
    'Z90u9EVf4M4',
    'yCJDmGrk8sM',
    'ymYtSum-2qc',
    'INNKxTAagE4',
    'zrP3muXzQX4',
    'vep9hSKc9I0',
    'wyIhJ3LMnRg',
    '_mwtz_8lBWc',
    'lY5TU8qHduM',
    'lin_ycbQGtE',
    'CXtHwJQphLI',
    '_zJ3_d1CODg',
    '0HEqwk9UMOc',
    'Z98SHl4nSFI',
    'FOkG5ScxU88',
    'ZBW6YozOu78',
    'gu-5cim8mpA',
    'a2kADxV0kBM',
    '2iIi1H9V-Hg',
    'xfOATs8ncLM',
    'DIMW-iHlDxE',
    'oxNF_GNuWpE',
    '84M1mVL0cjo',
    '7yqkfHo8Mwk',
    'guwVjGsg3h4',
    '4wX4mGuiTjw',
    'sGQrnPJSsPc',
    '6WRiPikxs-Q',
    'NztD5fYpXcg',
    'vSjgNxi7W-4',
    'nRxqSGBuB4s',
    'IkVazryUiko',
    'xVdW3yUCbuU',
    'gVZwfZVAuVE',
    '00kCzR10M1w',
    'Hfut9CfJhN0',
    'WahgsFhj3W0',
    'uqZ-mwxGf2c',
    'AcpVuvtSXwI',
    'JeqaHMmSh1s',
    'WMcKFQ200OE',
    'Wa0EHhhKV8Q',
    'jzjGcFkAnfs',
    'WdK7PED1ug8',
    'HiaotGxHTfo',
    'DazzkNtnzec',
    'ARWkoc3E8uE',
    'Th5MMOFQbh8',
    'SpNfrWmI8iE',
    'H-gkXATx8r0',
    '3ybGkjogcFQ',
    'QBUQvfZJpaM',
    '5Vloo08zQ7o',
    '5-ZNXQegVhs',
    'kQc99Io3pCo',
    'zwVDEAKKPZY',
    'cWozmWrqnxs',
    'joYJ6rPN3UI',
    'Qo3oJv4uyBI',
    'cEwAbu6FFRo',
    'IZX3_9rZeMU',
    'KDnTY0Svmr0',
    'qxOOl1hx1zU',
    '0Sed1oggMKY',
    'A96r5gqwUrI',
    'ZlEq2jFb8tI',
    'TmlqoKqMD2Y',
    '5st-kLcNrE8',
    'xV2EAL3NAVM',
    '2Ni8zfsxW6o',
    'd_0swhS1LyQ',
    'TDWC1fFhn9g',
    'V2LbQqD1lMM',
    'h31-NtagNoU',
    'o9yaniXkM-0',
    'RDa6WtZmW8E',
    'gBb1zn-QtY4',
    'Ul0ixBpd5iM',
    '43UjmZtW2JU',
    'US7oyxbcJCc',
    'DCGTYftRGWE',
    '3Fpey_L_XRU',
    'cJl2cchaHL8',
    'qbBA7GWZbu4',
    'P58Zt8A_1Mc',
    'MaP2i4dTiQk',
    'Pp36ysjfWd8',
    'JBh6rzeS-Qc',
    '9yov-ZVv-Bo',
    'xVmoqBYlQMU',
    '5KB2zLGjaps',
    'LWc3AAHoxnU',
    'Z06RjO-zFxI',
    'HOetEEw0ogM',
    '0NLj8g2hQNk',
    '0ttrfTfP864',
    'SeYrpzDTn6A',
    'FDYu2fllfuE',
    'tmerUd7eiy4',
    'tqDisu2tmG0',
    '9oSUtndLto4',
    'yOOQNnaOLeM',
    '4_mBGmXA244',
    'KCuGqld6nOc',
    'B2x09utLjtM',
    '7zFqW-ZcEbo',
    'js95nIDeA-c',
    'BAxPZdgmgRQ',
    'z_Ydy_-cI1U',
    'axvxGj3yOgA',
    'Xhq99-YHXCY',
    'PNFlYx8HiOM',
    'pzVOjl6mOD4',
    'olsB3bJxA2A',
    'IF5sNQH-01c',
    '2kvYb2pVe5o',
    'TLqdeHlAo3A',
    'o3ba6XdMQA0',
    'DTb0syknVSQ',
    '33odiiNMGzQ',
    'RvgI3oEThcA',
    'J6dRkXZhnIQ',
    '9tiUYnQL_y0',
    'OKXt-PJUuzE',
    'ykqWNyj1fHM',
    '4q9gLzti6Lk'
  ],
  security: [
    'kc1gwl89iyw',
    'Kp_4y_HEaZ0',
    'MFiVlaMYmwM',
    'infh5ZZwvLU',
    '_NXyqfM6TXg',
    '_5DCBqOCr8c',
    'u8XCBK6lGw0',
    'Zeg8zSOvoyE',
    'HxB-cJIbEgE',
    'taBP0Fr3uSQ',
    'CA1nlknmR3g',
    '1VjSLqfPf9s',
    'uhXcsWYhdkA',
    'Oa3jaLNSZvM',
    '1MPD6MILLcQ',
    'JfGgWiiCTA0',
    'FlGWkg8ih2Y',
    'MzdV5hjPdsI',
    'Hwa2vM9c2Xc',
    'neqE9X2kSuY'
  ],
  programming: [
    'T5FjMjTQCBI',
    'F6aMGDfVAFg',
    'D1Hth_78ftg',
    'gKYw0_jkNFI',
    'qyqLjeu8Hng',
    'iEn_PMcBlDk',
    'dsxuWtfzBGI',
    'GVq5DvGFLpI'
  ]
} as const

/**
 * Videos to hide from the showcase regardless of YouTube privacy status.
 * Auto-synced by sync-videos.ts — private/deleted videos detected during sync.
 * You can also add IDs here manually to exclude them from display.
 */
export const HIDDEN_VIDEO_IDS: ReadonlySet<string> = new Set([
  'J4nERLAJIbs',
  'md9nXDH1u7Q',
  'BNznoJHQDW0',
  'sZRIbxwHSCo',
  'JrCT7Xu-aGU',
  'hs7CiLpLgnY',
  'o3ba6XdMQA0',
  'DTb0syknVSQ',
  '33odiiNMGzQ',
  'RvgI3oEThcA',
  'J6dRkXZhnIQ',
  '9tiUYnQL_y0',
  'OKXt-PJUuzE',
  'ykqWNyj1fHM',
  '4q9gLzti6Lk',
  'FlGWkg8ih2Y',
  'MzdV5hjPdsI',
  'Hwa2vM9c2Xc',
  'neqE9X2kSuY',
  'mOVPWWSOZOU',
  'Wwa7kNVJPc4',
  'ivLskmc9YnU',
  '1cuMGVwrdLw',
  'Zop9xMGWjNk',
  'YeCnfTFPbtc',
  'brRRpsAaN9E',
])

export const allVideoIds = [
  ...VIDEO_CONFIG.korea,
  ...VIDEO_CONFIG.finance,
  ...VIDEO_CONFIG.kubernetes,
  ...VIDEO_CONFIG.development,
  ...VIDEO_CONFIG.security,
  ...VIDEO_CONFIG.programming
].filter((id) => !HIDDEN_VIDEO_IDS.has(id))

export const videoCategories: Record<string, keyof typeof VIDEO_CONFIG> = {}

Object.entries(VIDEO_CONFIG).forEach(([category, ids]) => {
  ids.forEach((id) => {
    videoCategories[id] = category as keyof typeof VIDEO_CONFIG
  })
})
